#!/usr/bin/env bash

args=($(printf "%s\n" $@))
cmd=${args[0]}
[[ "$@" != "${@% }" ]] && trail=1

result=($({
	my-fzf-list-files-shallow-first | grep '(directory)' &
	my-fzf-list-git-dirs
} | my-fzf-dir))
ret=$?

[[ $ret -ne 0 ]] && exit $ret
args+=(${result[1]})
echo "${args[@]} "

