#!/usr/bin/env bash

args=($(printf "%s\n" $@))
[[ "$@" == "${@% }" ]] && query=${args[${#args[@]}-1]}
[[ -d $query ]] && { init_dir=$query; query=''; }

result=($({
	my-fzf-list-files-shallow-first $init_dir &
	my-fzf-list-git-files
} | grep -v '(directory)' | my-fzf-file $query))
ret=$?

[[ $ret -ne 0 ]] && exit $ret
args+=(${result[1]})
echo "${args[@]} "

