#!/usr/bin/env bash

args=($(printf "%s\n" $@))
[[ "$@" != "${@% }" ]] && trail=1

result=($({
	my-fzf-list-files-shallow-first &
	my-fzf-list-git-files
} | grep -v '(directory)' | my-fzf-file))
ret=$?

[[ $ret -ne 0 ]] && exit $ret
args+=(${result[1]})
echo "${args[@]} "

