#!/usr/bin/env bash

# Inspiration:
# https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236

args=($(printf "%s\n" $@))
args[0]=git
cmd=${args[1]}
[[ "$@" == "${@% }" ]] && query=${args[${#args[@]}-1]}

# ==============================================================================
# LIST ALL COMMANDS
# ==============================================================================
function git-commands() {
	printf "%s\n" $(git help --all | grep '^ \+\w')
	git config --list | sed -n 's/^alias\.\([^=]\+\)=\(.*\)/\1 (alias for \2)/p'
}

# Check if command empty
if [[ -z $cmd ]]; then
	result=($(git-commands | my-fzf-40))
	ret=$?

# Check for command tab complete
elif [[ -z ${args[2]} && -n $query ]]; then
	result=($(git-commands | my-fzf-40 $cmd))
	ret=$?
fi

# Return results (if available)
if [[ -n $ret ]]; then
	[[ $ret -ne 0 ]] && exit $ret
	echo "git ${result[0]} "
	exit 0
fi


# ==============================================================================
# SPECIFIC COMMANDS
# ==============================================================================
if [[ $cmd =~ add|diff ]]; then
	result=($({
		my-fzf-list-git-files
	} | my-fzf-git-diff '!ignore'))
	ret=$?
	args+=(${result[1]})

elif [[ $cmd =~ show|revert ]]; then
	result=($({
		my-fzf-list-git-log $PWD
	} | my-fzf-git-hash))
	ret=$?
	args+=(${result[0]})

elif [[ $cmd =~ bco ]]; then
	result=($({
		git branch -vv -a
	} | my-fzf-40))
	ret=$?
	args+=(${result[0]})

else
	result=($({
		my-fzf-list-files-shallow-first
	} | my-fzf-git-diff))
	ret=$?
	args+=(${result[1]})
fi

# Return result
[[ $ret -ne 0 ]] && exit $ret
echo "${args[@]} "

